version: "3"
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181"
  kafkasvc:
    image: wurstmeister/kafka:2.11-1.1.1
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafkasvc:9092,OUTSIDE://localhost:19092
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:19092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "proto-spans:1:1,metricpoints:1:1,metric-data-points:1:1,mdm:1:1,metrics:1:1,graph-nodes:1:1,service-graph:1:1,mapped-metrics:1:1,anomalies:1:1,alerts:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "9092:9092"
      - "19092:19092"
  haystack-agent:
    image: expediadotcom/haystack-agent
    environment:
      JAVA_XMS: 128m
      haystack_env_agents_spans_port: 34000
    ports:
      - "34000:34000"

  frontend:
    image: expediadotcom/opentracing-spring-haystack-example
    environment:
      APP_MODE: frontend
      SPRING_PROFILE: remote
      HAYSTACK_AGENT_HOST: haystack-agent
      BACKEND_URL: http://backend:9091
    ports:
      - "9090:9090"

  backend:
    image: expediadotcom/opentracing-spring-haystack-example
    environment:
      APP_MODE: backend
      SPRING_PROFILE: remote
      HAYSTACK_AGENT_HOST: haystack-agent
