kind: Deployment
apiVersion: apps/v1beta2
metadata:
  labels:
    k8s-app: haystack-table
  name: replace_me
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: haystack-table
  template:
    metadata:
      labels:
        k8s-app: haystack-table
    spec:
      containers:
      - name: replace_me
        image: ashishagg0701/haystack-parquet-writer:1
        resources:
          limits:
            cpu: 250m
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 512Mi